### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by hamzamanzoor** [huwf/ltiauthenticator#1]
Hi,

I wanted to check if you have any usage instructions for this? Is it complete to the point that it adds JupyterHub to Canvas? I want to enable LTI authentication of JupyterHub and Nbgrader to auto-grade the assignments. 

Thanks

**Comment by huwf** [comment]
Hi,

It will not add jupyterhub to canvas itself, but will allow your jupyterhub
on a separate server to authenticate from the lti request that canvas
sends.

There are some things you will need to do manually on the canvas side, and
may also need to do some for your own implementation. I'll try and add some
instructions tonight when I'm back at my computer.

Huw

**Comment by hamzamanzoor** [comment]
Hi,

Following up with you on this. 

Can you send me the instructions? 

Thank you

**Comment by huwf** [comment]
Hi,

I just pushed some basic instructions to GitHub.  I don't have a setup to properly test things, but I'm hoping it should help you get started.

Huw
